blueprints/wikirenderer/__init__.py
from flask import Blueprint, render_template, abort, g, Markup
from jinja2 import TemplateNotFound

wikirenderer = Blueprint('renderer', __name__)

@wikirenderer.route('/')
@wikirenderer.route('/index')
def view_index():
    return view_page('index.md')


@wikirenderer.route('/<path:pagepath>')
def view_page(pagepath):
    page = g.wiki.get_page(pagepath)
    page_content = Markup(page.to_html())
    try:
        return render_template('default/page.html', content=page_content,
                               title=pagepath, docformat=page.docformat)
    except TemplateNotFound:
        abort(404)

wikicore/__init__.py
from .wiki import Wiki

from .page import WikiPage

templates/default/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-4.3.1.min.css') }}">

    <!-- Other CSS -->
    {% if docformat == 'markdown' %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/github-markdown.css') }}">
    {% endif %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/custom.css') }}">

    <title>{% if title %}{{ title }} - {% endif %}{{ g.wiki_name }}</title>
  </head>
  <body>
    <!-- Navbar -->
    {% include "default/navbar.html" %}

    <!-- Content -->
    <div class="container">
      <div class="row row-m-top">
        <div class="col {% if docformat == 'markdown' %}markdown-body{% endif %}">
          {% block content %}{% endblock %}
        </div>
      </div>
    </div>

    <!-- Bootstrap JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{{ url_for('static', filename='js/jquery-3.3.1.slim.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/popper-1.14.7.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap-4.3.1.min.js') }}"></script>
  </body>
</html>

templates/default/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{{ url_for('renderer.view_index') }}">{{ g.wiki_name }}</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    </ul>
    <form class="form-inline my-2 my-lg-0" action="/search" method="POST">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="searchterm">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

templates/default/page.html
{% extends "default/base.html" %}

{% block content %}
{{ content }}
{% endblock %}

templates/default/search.html
{% extends "default/base.html" %}

{% block content %}
<h1>Search results for '{{ searchterm }}':</h1>
{% if results %}
  <ul>
  {% for result in results %}
    <li>{{ result|safe }}</li>
  {% endfor %}
  </ul>
{% else %}
No results found.
{% endif %}
{% endblock %}